import React, {PropTypes} from 'react';

import {FormGroup, FormControl, Form, ControlLabel, Col, Alert, Checkbox, InputGroup, Button} from 'react-bootstrap';
import ClipboardButton from '../../../react/common/Clipboard';


export default React.createClass({

  propTypes: {
    requestedEmail: PropTypes.string.isRequired,
    incremental: PropTypes.bool.isRequired,
    delimiter: PropTypes.string.isRequired,
    enclosure: PropTypes.string.isRequired,
    onChange: PropTypes.func.isRequired,
    configId: PropTypes.string.isRequired
  },

  onChangeDelimiter(e) {
    this.props.onChange('delimiter', e.target.value);
  },

  onChangeEnclosure(e) {
    this.props.onChange('enclosure', e.target.value);
  },

  onChangeIncremental() {
    this.props.onChange('incremental', !this.props.incremental);
  },

  renderClipboardButton() {
    return (<ClipboardButton text={this.props.requestedEmail} label="Copy email" />);
  },

  renderResultInfo() {
    return (
      <Alert bsStyle="info">
         44 tables extracted. View the result in {this.renderBucketLink()} bucket.
      </Alert>
    );
  },

  renderBucketLink() {
    let bucket =  'in.c-keboola-ex-pigeon-' + this.props.configId;
    let link = 'https://connection.keboola.com/v2/storage/buckets/' + bucket;
    return (<a href={link}>{bucket}</a>);
  },

  getDefaultBucket() {
    return 'in.c-keboola-ex-pigeon-' + this.props.configId;
  },

  // getDefaultTable(configId) {
  //   return getDefaultBucket(configId) + '.data';
  // },


  render()  {
    return (
      <Form horizontal>
        <FormGroup>
          <Col componentClass={ControlLabel} sm={4}>
            Email
          </Col>
          <Col sm={8}>
            <InputGroup>
              <FormControl
                type="email"
                placeholder="Creating email, please wait"
                readOnly
                value={this.props.requestedEmail}
                title="Email generated by Pigeon"/>
              <InputGroup.Button>
                <Button bsSize="lg">
                  {this.renderClipboardButton()}
                </Button>
              </InputGroup.Button>
            </InputGroup>
          </Col>
        </FormGroup>
        <FormGroup>
          <Col componentClass={ControlLabel} sm={4}>
            Delimeter
          </Col>
          <Col sm={8}>
            <FormControl
              type="text"
              placeholder="Field delimeter used in CSV files"
              value={this.props.delimiter}
              onChange={this.onChangeDelimiter}/>
          </Col>
        </FormGroup>
        <FormGroup>
          <Col componentClass={ControlLabel} sm={4}>
            Enclosure
          </Col>
          <Col sm={8}>
            <FormControl
              type="text"
              placeholder="Field enclosure used in CSV files"
              value={this.props.enclosure}
              onChange={this.onChangeEnclosure}/>
          </Col>
        </FormGroup>
        <FormGroup>
          <Col componentClass={ControlLabel} sm={4}>
            Incremental
          </Col>
          <Col sm={8}>
            <Checkbox
              checked={this.props.incremental}
              onChange={this.onChangeIncremental}>
              Incremental load
          </Checkbox>
        </Col>
      </FormGroup>
      <br/>
      {this.renderResultInfo()}
    </Form>
    );
  }
});
