import React, {PropTypes} from 'react';

import {FormGroup, FormControl, Form, ControlLabel, Col, Alert, Checkbox, InputGroup, Button, HelpBlock} from 'react-bootstrap';
import ClipboardButton from '../../../react/common/Clipboard';
import CsvDelimiterInput from '../../../react/common/CsvDelimiterInput';


export default React.createClass({

  propTypes: {
    requestedEmail: PropTypes.string.isRequired,
    incremental: PropTypes.bool.isRequired,
    delimiter: PropTypes.string.isRequired,
    enclosure: PropTypes.string.isRequired,
    onChange: PropTypes.func.isRequired,
    configId: PropTypes.string.isRequired,
    tables: PropTypes.object.isRequired
  },

  onChangeDelimiter(e) {
    this.props.onChange('delimiter', e.target.value);
  },

  onChangeEnclosure(e) {
    this.props.onChange('enclosure', e.target.value);
  },

  onChangeIncremental() {
    this.props.onChange('incremental', !this.props.incremental);
  },

  renderClipboardButton() {
    return (<ClipboardButton text={this.props.requestedEmail} label="Copy email" />);
  },

  renderResultInfo() {
    let tableCount = this.getExtractedTables().count;
    if (tableCount === 0) {
      return (
        <Alert bsStyle="warning">
          {tableCount} tables extracted. Please check configuration and try run extraction again
        </Alert>
      );
    } else {
      return (
        <Alert bsStyle="info">
          {tableCount} tables extracted. View the result in {this.renderBucketLink()} bucket.
        </Alert>
      );
    }
  },

  getDefaultBucketName() {
    return 'in.c-keboola-ex-pigeon-' + this.props.configId;
  },

  renderBucketLink() {
    let bucketName =  this.getDefaultBucketName();
    let link = 'https://connection.keboola.com/v2/storage/buckets/' + bucketName;
    return (<a href={link}>{bucketName}</a>);
  },

  getExtractedTables() {
    return this.props.tables.has(this.getDefaultBucketName());
  },

  render()  {
    return (
      <Form horizontal>
        <FormGroup>
          <Col componentClass={ControlLabel} sm={4}>
            Email
          </Col>
          <Col sm={8}>
            <InputGroup>
              <FormControl
                type="email"
                placeholder="Creating email, please wait"
                readOnly
                value={this.props.requestedEmail}
                title="Email generated by Pigeon"/>
              <InputGroup.Button>
                <Button bsSize="lg">
                  {this.renderClipboardButton()}
                </Button>
              </InputGroup.Button>
            </InputGroup>
            <HelpBlock>Email generated by Pigeon.</HelpBlock>
          </Col>
        </FormGroup>
        <CsvDelimiterInput
          placeholder="Field delimeter used in CSV files"
          label="Delimiter"
          labelClassName="col-sm-4"
          wrapperClassName="col-sm-8"
          value={this.props.delimiter}
          onChange={this.onChangeDelimiter}
          help={(<span>Field delimiter used in CSV file. Default value is <code>,</code>. Use <code>\t</code> for tabulator.</span>)}
        />
        <FormGroup>
          <Col componentClass={ControlLabel} sm={4}>
            Enclosure
          </Col>
          <Col sm={8}>
            <FormControl
              type="text"
              placeholder="Field enclosure used in CSV files"
              value={this.props.enclosure}
              onChange={this.onChangeEnclosure}
            />
             <HelpBlock>Field enclosure used in CSV file. Default value is <code>"</code>.</HelpBlock>
          </Col>
        </FormGroup>
        <FormGroup>
          <Col componentClass={ControlLabel} sm={4}>
            Incremental
          </Col>
          <Col sm={8}>
            <Checkbox
              checked={this.props.incremental}
              onChange={this.onChangeIncremental}>
              Incremental load
            </Checkbox>
            <HelpBlock>If incremental load is turned on, table will be updated instead of rewritten. Tables with primary key will update rows, tables without primary key will append rows.</HelpBlock>
        </Col>
      </FormGroup>
      <br/>
      {this.renderResultInfo()}
    </Form>
    );
  }
});
