import React from 'react';
import InstalledComponentsActionCreators from '../../InstalledComponentsActionCreators';
import {Button} from './../../../../react/common/KbcBootstrap';
import Tooltip from './../../../../react/common/Tooltip';
import {Loader} from 'kbc-react-components';
import RoutesStore from '../../../../stores/RoutesStore';
import classnames from 'classnames';
import RunModal from './RunComponentButtonModal';

module.exports = React.createClass({
  displayName: 'RunExtraction',

  propTypes: {
    title: React.PropTypes.string.isRequired,
    mode: React.PropTypes.oneOf(['button', 'link']),
    component: React.PropTypes.string.isRequired,
    runParams: React.PropTypes.func.isRequired,
    method: React.PropTypes.string.isRequired,
    icon: React.PropTypes.string.isRequired,
    label: React.PropTypes.string,
    redirect: React.PropTypes.bool,
    tooltip: React.PropTypes.string,
    disabled: React.PropTypes.bool,
    disabledReason: React.PropTypes.string,
    tooltipPlacement: React.PropTypes.string,
    children: React.PropTypes.object
  },

  getDefaultProps: function() {
    return {
      mode: 'button',
      method: 'run',
      icon: 'fa-play',
      redirect: false,
      tooltip: 'Run',
      disabled: false,
      disabledReason: '',
      tooltipPlacement: 'top'
    };
  },

  getInitialState: function() {
    return {
      isLoading: false,
      showModal: false
    };
  },

  _handleRunStart: function() {
    var params;
    this.setState({
      isLoading: true
    });
    params = {
      method: this.props.method,
      component: this.props.component,
      data: this.props.runParams(),
      notify: !this.props.redirect
    };

    return InstalledComponentsActionCreators.runComponent(params)
      .then(this._handleStarted)
      .catch((function(_this) {
        return function(error) {
          _this.setState({
            isLoading: false
          });
          throw error;
        };
      })(this));
  },

  _handleStarted: function(response) {
    if (this.isMounted()) {
      this.setState({
        isLoading: false
      });
    }
    if (this.props.redirect) {
      return RoutesStore.getRouter().transitionTo('jobDetail', {
        jobId: response.id
      });
    }
  },

  render: function() {
    const tooltipDisabled = this.state.isLoading ? 'Component is running' : this.props.disabledReason;
    const tooltip = this.props.tooltip;

    const modal = (
      <RunModal
        onHide={() => this.setState({showModal: false})}
        show={this.state.showModal}
        title={this.props.title}
        body={this.props.children}
        onRequestRun={this._handleRunStart}
      />
    );

    if (this.props.disabled || this.state.isLoading) {
      return (
        <Tooltip
          tooltip={tooltipDisabled}
          placement={this.props.tooltipPlacement}
        >
          {this.props.mode === 'button' ? this._renderButton() : this._renderLink()}
        </Tooltip>
      );
    } else if (this.props.mode === 'button') {
      return (
        <Tooltip
          tooltip={tooltip}
          placement={this.props.tooltipPlacement}
        >
            {this._renderButton(modal)}
        </Tooltip>
      );
    } else {
      return this._renderLink(modal);
    }
  },

  onOpenButtonClick(e) {
    e.stopPropagation();
    e.preventDefault();
    this.setState({showModal: true});
  },

  _renderButton: function(modalComponent) {
    return (
      <Button
        className="btn btn-link"
        disabled={this.props.disabled || this.state.isLoading}
        onClick={this.onOpenButtonClick}
      >
        {modalComponent}
        {this._renderIcon()} {this.props.label ? ' ' + this.props.label : void 0}
      </Button>
    );
  },

  _renderLink: function(modalComponent) {
    return (
      <a className={
        classnames({
          'text-muted': this.props.disabled || this.state.isLoading
        })}
        onClick={this.onOpenButtonClick}
      >
        {modalComponent}
        {this._renderIcon()} {this.props.title}
      </a>
    );
  },

  _renderIcon: function() {
    if (this.state.isLoading) {
      return (<Loader className="fa-fw" />);
    } else {
      const className = 'fa fa-fw ' + this.props.icon;
      return (<i className={className} />);
    }
  }
});

// ---
// generated by coffee-script 1.9.2
