import keyMirror from 'fbjs/lib/keyMirror';

module.exports = {
  ActionTypes: keyMirror({
    CONFIG_ROWS_CREATE_START: null,
    CONFIG_ROWS_CREATE_SUCCESS: null,
    CONFIG_ROWS_CREATE_ERROR: null,

    CONFIG_ROWS_DELETE_START: null,
    CONFIG_ROWS_DELETE_SUCCESS: null,
    CONFIG_ROWS_DELETE_ERROR: null,

    CONFIG_ROWS_DISABLE_START: null,
    CONFIG_ROWS_DISABLE_SUCCESS: null,
    CONFIG_ROWS_DISABLE_ERROR: null,

    CONFIG_ROWS_ENABLE_START: null,
    CONFIG_ROWS_ENABLE_SUCCESS: null,
    CONFIG_ROWS_ENABLE_ERROR: null,

    CONFIG_ROWS_UPDATE_PARAMETERS: null,
    CONFIG_ROWS_RESET_PARAMETERS: null,

    CONFIG_ROWS_SAVE_PARAMETERS_START: null,
    CONFIG_ROWS_SAVE_PARAMETERS_SUCCESS: null,
    CONFIG_ROWS_SAVE_PARAMETERS_ERROR: null,

    CONFIG_ROWS_UPDATE_PROCESSORS: null,
    CONFIG_ROWS_RESET_PROCESSORS: null,

    CONFIG_ROWS_SAVE_PROCESSORS_START: null,
    CONFIG_ROWS_SAVE_PROCESSORS_SUCCESS: null,
    CONFIG_ROWS_SAVE_PROCESSORS_ERROR: null,

    CONFIG_ROWS_UPDATE_CONFIGURATION: null,
    CONFIG_ROWS_RESET_CONFIGURATION: null,

    CONFIG_ROWS_SAVE_CONFIGURATION_START: null,
    CONFIG_ROWS_SAVE_CONFIGURATION_SUCCESS: null,
    CONFIG_ROWS_SAVE_CONFIGURATION_ERROR: null
  })
};
